

module.exports = function(browser)
{
  browser
    .assert.hidden('#buyerSettings')
    .click('button#settingsBtn')
    .pause(1000)
    .assert.visible('#buyerSettings')
    .assert.visible('#buyerSettings #tab-profile.el-tabs__item')
    .assert.containsText('#buyerSettings #tab-profile.el-tabs__item', 'Profile')
    .click('#buyerSettings #tab-profile.el-tabs__item')
    .pause(1000)
    .assert.elementPresent('#buyerSettings form#profile input#firstName')
    .assert.elementPresent('#buyerSettings form#profile input#lastName')
    .assert.elementPresent('#buyerSettings form#profile input#phone')
    .assert.elementPresent('#buyerSettings form#profile input#email')
    .assert.elementPresent('#buyerSettings form#profile input#name')
    .assert.elementPresent('#buyerSettings form#profile input#address')
    .assert.elementPresent('#buyerSettings form#profile input#city')
    .assert.elementPresent('#buyerSettings form#profile input#state')
    .assert.elementPresent('#buyerSettings form#profile input#zip')
    .clearValue(`#buyerSettings form#profile input#firstName`)
    .setValue('#buyerSettings form#profile input#firstName', 'CVM')
    .clearValue(`#buyerSettings form#profile input#lastName`)
    .setValue('#buyerSettings form#profile input#lastName', 'Test')
    .clearValue(`#buyerSettings form#profile input#phone`)
    .setValue('#buyerSettings form#profile input#phone', '111-111-1111')
    .clearValue(`#buyerSettings form#profile input#email`)
    .setValue('#buyerSettings form#profile input#email', 'cvmtest0001@gmail.com')
    .clearValue(`#buyerSettings form#profile input#name`)
    .setValue('#buyerSettings form#profile input#name', 'CVM Test')
    .clearValue(`#buyerSettings form#profile input#address`)
    .setValue('#buyerSettings form#profile input#address', '1 Main Ave.')
    .clearValue(`#buyerSettings form#profile input#city`)
    .setValue('#buyerSettings form#profile input#city', 'San Jose')
    .clearValue(`#buyerSettings form#profile input#state`)
    .setValue('#buyerSettings form#profile input#state', 'CA')
    .clearValue(`#buyerSettings form#profile input#zip`)
    .setValue('#buyerSettings form#profile input#zip', '90101')
    .clearValue(`#buyerSettings form#profile button#updateProfile`)
    .click('#buyerSettings form#profile button#updateProfile')
    .pause(2500)
    .click('#buyerSettings button[aria-label=Close]')
    .pause(1000)
    .assert.hidden('#buyerSettings')
    .pause(1000);
}
